The IFT pipeline only is able to run a subset of the images. Here, we find the overlap between the images where floes are visible and where IFT successfully segmented the image.

In [1]:
# get list of evaluation tables
import pandas as pd
import os
eval_table_loc = "../data/ift_data/ift_pipeline_minarea_100px/eval_tables/"
files = os.listdir(eval_table_loc)

assign_table_loc = "../data/validation_tables/floe_labeling_tables/"
afiles = os.listdir(assign_table_loc)

df_eval = pd.concat([pd.read_csv(eval_table_loc + file) for file in files])
df_assign = pd.concat([pd.read_csv(assign_table_loc + file, index_col=0) for file in afiles if '.csv' in file])

In [2]:
df_assign['location'] = [x.replace(x.split('-')[0] + '-', '') for x in df_assign['long_name']]

In [3]:
df = df_assign.merge(df_eval[['location', 'preprocess', 'tracker']], left_on='location', right_on='location', how='inner')

In [4]:
df_eval.columns

Index(['location', 'center_lat', 'center_lon', 'top_left_lat', 'top_left_lon',
       'lower_right_lat', 'lower_right_lon', 'left_x', 'right_x', 'lower_y',
       'top_y', 'startdate', 'enddate', 'soit', 'landmasks', 'preprocess',
       'extractH5', 'tracker'],
      dtype='object')

In [5]:
df.loc[df.tracker=='pass'].sort_values('case_number').loc[:, ['case_number', 'region', 'fl_analyst', 'tracker']]

    case_number                     region fl_analyst tracker
83            7                 baffin_bay         MK    pass
43           23                 baffin_bay         ES    pass
44           32                 baffin_bay         ES    pass
46           45                 baffin_bay         ES    pass
0            99               beaufort_sea         EB    pass
39          110               beaufort_sea         ES    pass
22          122               beaufort_sea         ER    pass
23          142               beaufort_sea         ER    pass
24          146               beaufort_sea         ER    pass
12          229  chukchi-east_siberian_sea         EB    pass
8           263              greenland_sea         EB    pass
30          283              greenland_sea         ER    pass
51          286              greenland_sea         ES    pass
53          302                 hudson_bay         ES    pass
15          329                 hudson_bay         EB    pass
16          339                 hudson_bay         EB    pass
58          385                 laptev_sea         ES    pass

In [6]:
labeled_floes = [x for x in os.listdir('../data/validation_images/labeled_floes_png/') if 'png' in x]
labeled_landfast = [x for x in os.listdir('../data/validation_images/labeled_landfast_png/') if 'png' in x]
landmask = [x for x in os.listdir('../data/validation_images/landmask_png/') if 'png' in x]

In [9]:
labeled_floes.sort()
labeled_floes

['000_baffin_bay_20040725_aqua_labeled_floes.png',
 '000_baffin_bay_20040725_terra_labeled_floes.png',
 '005_baffin_bay_20050827_aqua_labeled_floes.png',
 '005_baffin_bay_20050827_terra_labeled_floes.png',
 '007_baffin_bay_20070605_aqua_labeled_floes.png',
 '007_baffin_bay_20070605_terra_labeled_floes.png',
 '008_baffin_bay_20080704_aqua_labeled_floes.png',
 '016_baffin_bay_20090426_aqua_labeled_floes.png',
 '016_baffin_bay_20090426_terra_labeled_floes.png',
 '019_baffin_bay_20110506_aqua_labeled_floes.png',
 '019_baffin_bay_20110506_terra_labeled_floes.png',
 '021_baffin_bay_20120422_aqua_labeled_floes.png',
 '021_baffin_bay_20120422_terra_labeled_floes.png',
 '022_baffin_bay_20130308_aqua_labeled_floes.png',
 '022_baffin_bay_20130308_terra_labeled_floes.png',
 '023_baffin_bay_20140329_aqua_labeled_floes.png',
 '023_baffin_bay_20140329_terra_labeled_floes.png',
 '028_baffin_bay_20160708_terra_labeled_floes.png',
 '032_baffin_bay_20190523_aqua_labeled_floes.png',
 '032_baffin_bay_20190523_terra_labeled_floes.png',
 '033_baffin_bay_20190925_aqua_labeled_floes.png',
 '033_baffin_bay_20190925_terra_labeled_floes.png',
 '036_baffin_bay_20210602_aqua_labeled_floes.png',
 '036_baffin_bay_20210602_terra_labeled_floes.png',
 '037_baffin_bay_20210804_aqua_labeled_floes.png',
 '037_baffin_bay_20210804_terra_labeled_floes.png',
 '045_baffin_bay_20220530_aqua_labeled_floes.png',
 '045_baffin_bay_20220530_terra_labeled_floes.png',
 '046_baffin_bay_20220617_aqua_labeled_floes.png',
 '046_baffin_bay_20220617_terra_labeled_floes.png',
 '050_barents-kara_seas_20040519_aqua_labeled_floes.png',
 '050_barents-kara_seas_20040519_terra_labeled_floes.png',
 '081_barents-kara_seas_20140708_aqua_labeled_floes.png',
 '081_barents-kara_seas_20140708_terra_labeled_floes.png',
 '092_barents-kara_seas_20200701_aqua_labeled_floes.png',
 '092_barents-kara_seas_20200701_terra_labeled_floes.png',
 '107_beaufort_sea_20030616_aqua_labeled_floes.png',
 '107_beaufort_sea_20030616_terra_labeled_floes.png',
 '110_beaufort_sea_20040428_aqua_labeled_floes.png',
 '110_beaufort_sea_20040428_terra_labeled_floes.png',
 '118_beaufort_sea_20100925_aqua_labeled_floes.png',
 '118_beaufort_sea_20100925_terra_labeled_floes.png',
 '122_beaufort_sea_20140818_aqua_labeled_floes.png',
 '122_beaufort_sea_20140818_terra_labeled_floes.png',
 '140_beaufort_sea_20200708_aqua_labeled_floes.png',
 '140_beaufort_sea_20200708_terra_labeled_floes.png',
 '142_beaufort_sea_20210427_aqua_labeled_floes.png',
 '142_beaufort_sea_20210427_terra_labeled_floes.png',
 '146_beaufort_sea_20220523_aqua_labeled_floes.png',
 '146_beaufort_sea_20220523_terra_labeled_floes.png',
 '165_bering_strait_20090523_aqua_labeled_floes.png',
 '165_bering_strait_20090523_terra_labeled_floes.png',
 '208_chukchi-east_siberian_sea_20100929_aqua_labeled_floes.png',
 '208_chukchi-east_siberian_sea_20100929_terra_labeled_floes.png',
 '281_greenland_sea_20170805_aqua_labeled_floes.png',
 '281_greenland_sea_20170805_terra_labeled_floes.png',
 '283_greenland_sea_20180610_aqua_labeled_floes.png',
 '283_greenland_sea_20180610_terra_labeled_floes.png',
 '286_greenland_sea_20200318_aqua_labeled_floes.png',
 '286_greenland_sea_20200318_terra_labeled_floes.png',
 '290_greenland_sea_20220723_aqua_labeled_floes.png',
 '290_greenland_sea_20220723_terra_labeled_floes.png',
 '300_hudson_bay_20050613_aqua_labeled_floes.png',
 '300_hudson_bay_20050613_terra_labeled_floes.png',
 '301_hudson_bay_20060329_aqua_labeled_floes.png',
 '301_hudson_bay_20060329_terra_labeled_floes.png',
 '302_hudson_bay_20060403_aqua_labeled_floes.png',
 '302_hudson_bay_20060403_terra_labeled_floes.png',
 '318_hudson_bay_20080813_aqua_labeled_floes.png',
 '318_hudson_bay_20080813_terra_labeled_floes.png',
 '319_hudson_bay_20090605_aqua_labeled_floes.png',
 '319_hudson_bay_20090605_terra_labeled_floes.png',
 '324_hudson_bay_20110323_aqua_labeled_floes.png',
 '324_hudson_bay_20110323_terra_labeled_floes.png',
 '325_hudson_bay_20110327_aqua_labeled_floes.png',
 '325_hudson_bay_20110327_terra_labeled_floes.png',
 '340_hudson_bay_20210518_aqua_labeled_floes.png',
 '340_hudson_bay_20210518_terra_labeled_floes.png',
 '351_laptev_sea_20070405_aqua_labeled_floes.png',
 '351_laptev_sea_20070405_terra_labeled_floes.png',
 '353_laptev_sea_20070712_aqua_labeled_floes.png',
 '353_laptev_sea_20070712_terra_labeled_floes.png',
 '360_laptev_sea_20080330_aqua_labeled_floes.png',
 '360_laptev_sea_20080330_terra_labeled_floes.png',
 '362_laptev_sea_20080601_aqua_labeled_floes.png',
 '362_laptev_sea_20080601_terra_labeled_floes.png',
 '377_laptev_sea_20130904_aqua_labeled_floes.png',
 '377_laptev_sea_20130904_terra_labeled_floes 2.png',
 '377_laptev_sea_20130904_terra_labeled_floes.png',
 '379_laptev_sea_20140403_aqua_labeled_floes.png',
 '379_laptev_sea_20140403_terra_labeled_floes.png',
 '385_laptev_sea_20180601_aqua_labeled_floes.png',
 '385_laptev_sea_20180601_terra_labeled_floes.png',
 '419_sea_of_okhostk_20130629_aqua_labeled_floes.png',
 '419_sea_of_okhostk_20130629_terra_labeled_floes.png']

In [52]:
# 118 beaufort terra missing
# It was assigned to ethan, but not in folder
df_assign.loc[df_assign.case_number==118]

,case_number,long_name,region,start_date,end_date,fl_analyst,location
1,118,118-beaufort_sea-100km_by_100km-20100925-20100926,beaufort_sea,2010-09-25,2010-09-26,ER,beaufort_sea-100km_by_100km-20100925-20100926